### ISSUE TITLE
Bug: Deletion of namespaces

### ISSUE THREAD

**Issue by sybnex** [projectcapsule/capsule#1181]
# Bug description
Due to the change from Capsule 0.6.x to 0.7.x you've changed the CRD handling. In the past we used a special way to workaround this handling because of some issues in our deployment chain. After your new release we tried to remove that special handling.

Unfortunately  I made a **big** mistake over there which has deleted all the CRDs from capsule and reinstalled them. Including all our Tenants. Our pipeline recreated afterwards all the "missing" tenants.

But then, the capsule-controller started to **delete** all the namespaces which had now a bad owner reference which was really bad as u can imagine. Including PVCs, special config and so on and so on.

I can only blame myself for issue for sure but => 

I really struggle with the feature, that the capsule-controller was starting the delete the namespaces. I mean I could have write a script to change the owner reference, but deleting? serious? 

Blame me again if I'm wrong, but after stopping the capsule-controller, the deleting of the namespaces stopped as well.

IMHO: Capsule should not delete any namespace. Even when I delete a tenant i could still to that manual by running a label filter. Or maybe you can add an option for that.

# How to reproduce

Steps to reproduce the behavior (I guess, did not tested this): 

1. install capsule
2. create some tenants with namespaces attached
3. delete the crd tenant
4. reinstall the crd tenant
5. create the same some tenants with namespaces attached

# Logs

I don't have any logs as I had pressure to make a whole Kubernetes restore (disaster recovery test, check). 

# Additional context

- Capsule version: 0.7.x
- Helm Chart version: latest
- Kubernetes version: 1.29.6

**Comment by oliverbaehler** [comment]
Hi @sybnex, Thanks for reporting that. I have had once the same issue, so I understand your frustration.

We don't delete namespaces, or at least i am not aware of that. The deletion was probably triggered by the [Cascading Deletion](https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/). Since the parent tenant was deleted. I will take a wild guess and assume you just stopped the controller but left the validating-webhooks for capsule as they are. This caused the Delete Operations for namespaces to run into a timeout and therefor the deletion stopped. But I would need more information to confirm that.

 The new tenants are new entities and are not matched with the old ones. The only thing that would happen from our side, is that we are dropping updates for that namespaces. Or at least with the old ownerreference.

For the internal workings we need these ownerreferences, so we can't drop these. However we could consider allowing to define finalizers on tenant basis. Then you as administrator can handle the garbage collection by yourself. 

@prometherion Please correct me if I am wrong and let me know what you think about it.

Were you able to fully recover?

**Comment by prometherion** [comment]
You're correct, Oliver, it's the cascading deletion upon a CRD deletion, and this shouldn't done to avoid these kinds of failure, sorry to hear this @sybnex.

The boundary between a Namespace and a Tenant is the Owner Reference, we have some restore scripts a customer of ours used for Velero.

Despite the outage, I'm thinking what we could do to improve the upgrade instructions, and I'm thinking the critical aspect here is about the fact we changed the lifecycle of CRDs.

**Comment by sybnex** [comment]
Thanks for listening ... :)

We could fully recover by an etcd restore from half an hour before. Lost some PVCs where we didn't provided backup, so expected. The "badest" thing was, we had an empty Kafka afterwards and telling our devs to rerun all their pipelines. But in the end, not so bad for a full outage.

So why is the OwnerReference that hard needed? Why a label is not enough maybe with the ID of the tenant to stay unique?

**Comment by oliverbaehler** [comment]
Well mainly because the functionality provided is intended as is. So if a tenant is deleted, all its namespaces should also be deleted. In zhe end you would just mimic something with annotations what's already solved by ownerreferences. 

Counter-Question: How about patching in finalizers manually?

**Comment by sybnex** [comment]
So we have 131 tenants in every Kubernetes cluster. Patching the finalizer I would have to do twice in the lifetime of a tenant which makes no sense for me. 

I will go with _kyverno_ and restrict the deletion of namespaces, hopefully that helps. I already have the rule to restrict deleting tenants itself, but of course not the whole tenant crd, lol. 

IMHO the deletion of the namespace is wrong for me, because even in reallife, if you delete a tenant it will take weeks to get rid of all the traces. I would start deleting deployment, services, after backup even pvs, and so on. And at the end I would delete an empty namespace with the tenant together.

Thanks for discussion, if there will be no further action this issue can be closed.

PS: @oliverbaehler we could have another round with a beer maybe ;)

**Comment by prometherion** [comment]
> I will go with _kyverno_ and restrict the deletion of namespaces, hopefully that helps. I already have the rule to restrict deleting tenants itself, but of course not the whole tenant crd, lol.

JFI, we have a knob that allows stopping the deletion of the Tenant resource, `tnt.spec.preventDeleation`

```
   preventDeletion       <boolean>
    Prevent accidental deletion of the Tenant. When enabled, the deletion
    request will be declined.
```

Of course, if you delete the Custom Resource Definition, there is nothing we can do there.

> IMHO the deletion of the namespace is wrong for me, because even in reallife, if you delete a tenant it will take weeks to get rid of all the traces. I would start deleting deployment, services, after backup even pvs, and so on. And at the end I would delete an empty namespace with the tenant together.

These kinds of feedback are very welcomed. We designed Capsule with self-service capabilities to decrease the operational burden, especially for the onboarding phase, as well as the offboarding such as deleting a Tenant that could be a customer, a dev environment, etc.

> PS: @oliverbaehler we could have another round with a beer maybe ;)

Hey, extend the invitation, I want to join you for the beer! 🫠

**Comment by sybnex** [comment]
Issue can be closed.

I fixed this behavior in our environment by deleting the helm secret, so that helm is not deleting the CRDs on the next run.

**Comment by oliverbaehler** [comment]
@prometherion FYI just implemented something similar. You can unset these fields:
```
					ownerRefs[i].BlockOwnerDeletion = nil
					ownerRefs[i].Controller = nil
```

This keeps the ownerreference, but does not delete cascading. However you are then stuck with n-ownerrefs which point to nowhere and arent reconciled.
