### ISSUE TITLE
capsule:v0.7.2 image does not exist

### ISSUE THREAD

**Issue by mallenLF** [projectcapsule/capsule#1240]
# Bug description

There is no "capsule" OCI image artifact with tag v0.7.2. There is a charts/capsule artifact with the v0.7.2 tag, however. I also notice that Artifact Hub doesn't list the chart for v0.7.2.

# How to reproduce

docker pull ghcr.io/projectcapsule/capsule:v0.7.2
Error response from daemon: failed to resolve reference "ghcr.io/projectcapsule/capsule:v0.7.2": ghcr.io/projectcapsule/capsule:v0.7.2: not found

# Expected behavior

docker pull starts pull v0.7.2 from projectcapsule/capsule

# Logs

N/A

# Additional context

N/A

**Comment by oliverbaehler** [comment]
Docker image is now released, trivy had problems downloading the vuln db :/. Chart is being released because GH Token expired.

**Comment by mallenLF** [comment]
`docker pull ghcr.io/projectcapsule/capsule:v0.7.2` works for me now. Thank you.

Perhaps this is what you meant by the GH token being expired, but I do notice that the link to Artifact Hub for the v0.7.2 chart, https://artifacthub.io/packages/helm/projectcapsule/capsule/0.7.2, still does not work -- the page says "Sorry, the package you requested was not found." I got this link from the Releases page for the v0.7.2 release. v0.7.1 is registered on Artifact Hub.

**Comment by oliverbaehler** [comment]
Published
