### ISSUE TITLE
Update projectcapsule/capsule repo about information with new website URL

### ISSUE THREAD

**Issue by nate-double-u** [projectcapsule/capsule#1243]
Hello,

I was making an update to CloMonitor (https://clomonitor.io/projects/cncf/capsule), when i noticed that the website URL hadn't updated.

As per https://github.com/cncf/clomonitor/pull/1615#issuecomment-2446044233, the website info is taken from the website set in the repository, not at the organization level. So I think if we update it in this repo it should propagate to CloMonitor (and it'll be correct here 😊)

**Comment by nate-double-u** [comment]
<img width="622" alt="381432050-133924e0-3b03-43b0-bd61-3ac47f711a6e" src="https://github.com/user-attachments/assets/e9b5cbce-c9be-405d-835f-f0e59ee55e8f">

**Comment by oliverbaehler** [comment]
@nate-double-u thanks for the ping, updated the URL

**Comment by nate-double-u** [comment]
I see this has been updated now on CloMonitor too (https://clomonitor.io/projects/cncf/capsule)

Thanks!
