### ISSUE TITLE
Cluster admin actions are intercepted as tenant owner and cluster level create actions are blocked  by capsule

### ISSUE THREAD

**Issue by gowthamvasan** [projectcapsule/capsule#1292]
# Bug description

My user is part of both cluster admin and tenant owner for development purpose. We enforced -force-tenant-prefix for namespace creation for each tenants. When i create new namespace at cluster level, capsule rejects my request saying "Error from server (Forbidden): admission webhook "namespaces.projectcapsule.dev" denied the request: The namespace doesn't match the tenant prefix, expected"

# How to reproduce

1. Provide the Capsule Tenant YAML definitions
2. Provide all managed Kubernetes resources

# Expected behavior

When i switch to cluster admin user, i should be able to create new namespace out of the scope of each tenant. But I am able to list the all namespaces at the cluster level. Only creation of namespaces fails

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
{"level":"debug","ts":"2024-12-09T14:21:22.430Z","logger":"events","msg":"Namespace admin-test has been assigned to the desired Tenant","type":"Normal","object":{"kind":"Tenant","name":"******","uid":"7b5a4f38-8cb0-4234-8baf-5fca5f5e0f46","apiVersion":"capsule.clastix.io/v1beta2","resourceVersion":"102146189"},"reason":"NamespaceCreationWebhook"}
{"level":"debug","ts":"2024-12-09T14:21:22.521Z","logger":"events","msg":"Namespace admin-test does not match the expected prefix for the current Tenant","type":"Warning","object":{"kind":"Tenant","name":"********","uid":"7b5a4f38-8cb0-4234-8baf-5fca5f5e0f46","apiVersion":"capsule.clastix.io/v1beta2","resourceVersion":"102146189"},"reason":"InvalidTenantPrefix"}

# Additional context

- Capsule version: v0.7.0
- Helm Chart version: capsule-0.7.0
- Kubernetes version: (`v1.31.1`)

**Comment by oliverbaehler** [comment]
Hi @gowthamvasan, a user is either a capsule user or not. You need to impersonate as a serviceaccount with the same privileges, which is not part of the capsuleUsers or remove admins from the capsuleUsers.

**Comment by gowthamvasan** [comment]
@oliverbaehler  Thanks. So either be a capsule user or a cluster admin . we cannot be both .
