### ISSUE TITLE
capsule-controller-manager is CrashLoopBackOff

### ISSUE THREAD

**Issue by zhenlohuang** [projectcapsule/capsule#829]
# Bug description

capsule-controller-manager is CrashLoopBackOff via helm install.

# Reproduced Steps
```
helm repo add clastix https://clastix.github.io/charts
helm install capsule clastix/capsule -n fusionx --create-namespace
```

# Expected behavior

capsule-controller-manager start successfully.

# Logs
```
{"level":"info","ts":"2023-10-18T08:19:35.028Z","logger":"setup","msg":"Capsule Version v0.3.3 64513b8"}
{"level":"info","ts":"2023-10-18T08:19:35.028Z","logger":"setup","msg":"Build from: https://github.com/clastix/capsule"}
{"level":"info","ts":"2023-10-18T08:19:35.028Z","logger":"setup","msg":"Build date: 2023-06-27T17:12:25"}
{"level":"info","ts":"2023-10-18T08:19:35.028Z","logger":"setup","msg":"Go Version: go1.19.10"}
{"level":"info","ts":"2023-10-18T08:19:35.028Z","logger":"setup","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":"2023-10-18T08:19:35.030Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2023-10-18T08:19:35.133Z","logger":"controllers.TLS","msg":"Generating new TLS certificate"}
{"level":"error","ts":"2023-10-18T08:20:31.331Z","logger":"controllers.TLS","msg":"cannot update Capsule TLS","error":"client rate limiter Wait returned an error: context canceled","stacktrace":"github.com/clastix/capsule/controllers/tls.Reconciler.ReconcileCertificates\n\t/workspace/controllers/tls/manager.go:110\nmain.main\n\t/workspace/main.go:183\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"error","ts":"2023-10-18T08:20:31.332Z","logger":"setup","msg":"unable to reconcile Capsule TLS secret","error":"client rate limiter Wait returned an error: context canceled","stacktrace":"main.main\n\t/workspace/main.go:184\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

# Additional context

- Capsule version: 0.3.3
- Helm Chart version: 0.4.6
- Kubernetes version: v1.28.1+rke2r1

**Comment by prometherion** [comment]
Thanks for opening this, @zhenlohuang!

May I ask you to give a try in increasing the deployment resources, especially CPU?

The first startup is responsible in creating the certificates, and it could take some time, causing then a loopbackoff.

**Comment by zhenlohuang** [comment]
We double the cpu and memory, however it doesn't work. The crash still happened.

Is there any workaround to disable the cert creating or increase the timeout?

**Comment by prometherion** [comment]
You can offload certificate creation to cert-manager, if you have it installed.

https://github.com/projectcapsule/capsule/blob/9a21b408dde54c9d6522a0651135f76701dac263/charts/capsule/values.yaml#L9-L10

https://github.com/projectcapsule/capsule/blob/9a21b408dde54c9d6522a0651135f76701dac263/charts/capsule/values.yaml#L54-L55

https://github.com/projectcapsule/capsule/blob/9a21b408dde54c9d6522a0651135f76701dac263/charts/capsule/values.yaml#L158-L160

Let me know if this works for you, and maybe I could ask you to contribute to the documentation explaining how to install Capsule with cert-manager: WDYT?

**Comment by prometherion** [comment]
@zhenlohuang please, can you provide some feedback about your issue? It would be helpful for the community and members who could potentially face the same issue!

**Comment by oliverbaehler** [comment]
@zhenlohuang We will close this issue for now, reopen if you need further assistance.
