### ISSUE TITLE
Update dead links in documentation

### ISSUE THREAD

**Issue by larsgerber** [projectcapsule/capsule#933]
# Bug description

Hello everyone

While consulting the documentation, I clicked on an external link and was greeted by a 404 page from Github.

I shortly checked why. In the commit [#docs:movin](https://github.com/projectcapsule/capsule/commit/7ea8ff632764688113e87ef4cb72690fbeb0d5bb)  the links have been changed from github.com/clastix to github.com/projectcapsule and the dead link was the only one that is not valid under the new address.

I briefly searched the entire document for all links and checked whether they still work. I only found one more.

# How to reproduce

First link
1. Go to https://github.com/search?q=repo%3Aprojectcapsule%2Fcapsule+https%3A%2F%2Fgithub.com%2Fprojectcapsule%2Fcapsule-lens-extension&type=code
2. Open the highlighted link.

Second link
1. Go to https://github.com/search?q=repo%3Aprojectcapsule%2Fcapsule+kubernetes.io%2Fdocs%2Freference%2Fgenerated%2Fkubernetes-api%2Fv1.20&type=code
2. Open the highlighted link.

# Expected behavior

The link refers to a functioning page.

First link: https://github.com/clastix/capsule-lens-extension
Second link: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#objectmeta-v1-meta

**Comment by prometherion** [comment]
A bug when we moved to the vendor-neutral GH organization, thanks for reporting this!

Are yo up to work on a fix?

**Comment by larsgerber** [comment]
You're welcome @prometherion. Not yet. But I can create a PR for the links in the evening if thats okey.

**Comment by prometherion** [comment]
Closes via #935.
