### ISSUE TITLE
Donate maxgio92/capsule-addon-fluxcd

### ISSUE THREAD

**Issue by maxgio92** [projectcapsule/capsule#936]
Hello,
I'd like to donate an addon ([maxgio92/capsule-addon-fluxcd](https://github.com/maxgio92/capsule-addon-fluxcd)) I developed for the integration of Capsule with GitOps scenarios made with Flux CD (v2), following the documented [integration guide](https://capsule.clastix.io/docs/guides/flux2-capsule) that describes a use case to provide tenants a Namespace-as-a-Service the GitOps-way.

The addon simply automates all the Tenant owner ServiceAccount setup for:
* Required permissions
* Credentials and client config (kubeConfig) to be used in Flux [reconciliation](https://fluxcd.io/flux/concepts/#reconciliation) resources.

The setup aligns with all the Flux [multi-tenancy lockdown](https://fluxcd.io/flux/installation/configuration/multitenancy/) security rules, which are fundamental for multi-tenancy scenarios.

This setup, as for the integration documentation, introduces a pattern that is the Tenant system `Namespace`.
This `Namespace` is outside the `Tenant` and it contains all system resources, such as:
* The `ServiceAccount` Tenant owner
* The `Rolebinding`s
* The client config for the Service Account `Tenant` owner

These resources are intended to be used by the Flux [reconciliation](https://fluxcd.io/flux/concepts/#reconciliation) resources, in order to reconcile Tenant resources as Tenant owner.
Furthermore, with the autogenerated client config, all the requests are directed to the API server through the Capsule proxy, allowing the tenant to operate, the GitOps-way, on cluster-wide resources, including the custom ones.

The addon allows to optionally distribute the Tenant owner client config in all `Tenant`'s `Namespace`s through `GlobalTenantResource`s. This is configurable as a per-owner knob.

More on this in the addon's [home](https://github.com/maxgio92/capsule-addon-fluxcd/tree/main#how-it-works).

**Comment by prometherion** [comment]
LGTM, I'm looking forward to having it donated to the Project Capsule organization! 👍🏻

**Comment by maxgio92** [comment]
We had the [feedback](https://kubernetes.slack.com/archives/C03GETTJQRL/p1704570438570289?thread_ts=1704036440.917509&cid=C03GETTJQRL) in the Slack channel also from @bsctl.
So we have 2 positive feedbacks from 2 maintainers, within 9 days.
I think I can now request the transfer WDYT @prometherion?

**Comment by prometherion** [comment]
@maxgio92 please, proceed with the repo transfer to the `projectcapsule` organization.

Closing this, and welcome aboard!

**Comment by maxgio92** [comment]
Thank you @prometherion!
Just sent the ownership transfer.
