### ISSUE TITLE
Propose for serving in the role of maintainer

### ISSUE THREAD

**Issue by maxgio92** [projectcapsule/capsule#962]
Hello everyone,
this issue tracks my proposal for serving in the role of maintainer for the projects:
* capsule
* capsule-proxy

I think that my involvement in both projects grew over time and with it, my pleasure in contributing to them.

I'd be glad to have the duty of helping maintain the projects, as well as contributing to shaping their evolution.

I open this issue as a request for comments from the maintainers @prometherion @bsctl @oliverbaehler @MaxFedotov.

Cheers,
Max

**Comment by oliverbaehler** [comment]
@maxgio92 Happy to have you onboard, please prepare the mrs to add yourself to the relevant files etc. Once merge we ll grant permissions on the project

**Comment by maxgio92** [comment]
@oliverbaehler thank you!
PTAL:
- #969
- https://github.com/projectcapsule/capsule-proxy/pull/385

**Comment by prometherion** [comment]
Happy to have you, Max :)

**Comment by maxgio92** [comment]
Thank you! ❤️
