### ISSUE TITLE
feat: change soft references to clastix.io

### ISSUE THREAD

**Issue by oliverbaehler** [projectcapsule/capsule#998]
# Describe the feature

We can start migrating to `projectcapsule.dev` from `capsule.clastix.io`. This is just preparation for a future v1 release. Places i can think of where these references can be changed without big changes:

  * `Webhook-Names`
  * `Default userGroups`
  * `E2E tests`
  * `Documentation`

# What would the new user story look like?

How would the new interaction with Capsule look like? E.g.

1. What are the prerequisites for this?
2. Tenant owner creates a new _Namespace_
3. This is going to be attached to the _Tenant_
4. All the magic happens in the background

Feel free to add a diagram if that helps explain things.

# Expected behavior
A clear and concise description of what you expect to happen.

**Comment by prometherion** [comment]
Marking this as a breaking change since users must be aware of the renaming of the default user group from `capsule.clastix.io` to `projectcapsule.dev`.
